### ISSUE TITLE
Alternative Custom Filed Names

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pixel-banner#28]
Hi there! It's me again! 😄

I really appreciate the customizable field name feature; however, I would love to see an additional option for an `alternative file name`. 😈
![image](https://github.com/user-attachments/assets/e288baed-b17c-4989-9c49-6c2d6f70061d)

---

This idea was inspired by the plugin **Front Matter Title**, which offers two options:
![image](https://github.com/user-attachments/assets/dee8eff8-e248-4d96-8b3d-b2925b86a1ca)

First, it attempts to resolve the `title` property, and if that doesn't exist, it falls back to `_basename` property.

I believe that adding this feature would enhance the compatibility of the **Pexels banner** with other plugins (yes, I'm referring to **Banners**). For users transitioning from Banners, if the default alternative name is set to `image`, they would be able to see the original image effects without needing to make any additional adjustments!

Furthermore, I genuinely think this plugin could completely replace the outdated Banners plugin. Great job!  🥳

---

By the way, the new plugin settings page is both beautiful and user-friendly!  I love it!

**Comment by jparkerweb** [comment]
great idea!
I might consider making each field a "comma delimited list". similar to the default keywords, you could specify one to many names for each field (separated by comma).  will need to think about unique name validation, if I should allow, spaces, etc., but I think it is doable.

**Comment by jparkerweb** [comment]
@Moyf  added and fixed

**Comment by Moyf** [comment]
> @Moyf added and fixed

WOW Great! Really appreciate it, thank you!
