### ISSUE TITLE
Stopped working Obsidian 1.7.4

### ISSUE THREAD

**Issue by CrispisFoundry** [jparkerweb/pixel-banner#35]
Pixel banner stopped working for me, probably after Obsidian Update, I'm at 1.7.4 now.
Reinstalled and got API key from Pixabay, still nothing.
The option to add a banner is still there in add properties but no images appear.

**Comment by jparkerweb** [comment]
@CrispisFoundry 
Please do the following:
- confirm you have Pixel Banner 2.3.1 installed
- open dev tools in Obsidiain (Ctrl + i) and see if there are any errors in the console tab
- download the example vault in this repo and see if that is working for you:
https://github.com/jparkerweb/pixel-banner/raw/refs/heads/main/example-vault.zip

**Comment by CrispisFoundry** [comment]
Hi Justin :)

Yes, have version 2.3.1 installed.
In console there were a few errors, but I have no idea what they mean, nor
if they are related to pixelbanner.
I opened the  test vault and tried the test notes : no banner visible.

I opened the console again, and there were no errors.

Sorry for the trouble

Greetings

Chris

**Comment by CrispisFoundry** [comment]
Hi, again lol :)

Problem solved : just entered "banner" as a property name and stopped using
"Pexel-banner".
All pretty stupid, but he 🤷

Greetings

Chris

**Comment by jparkerweb** [comment]
hehe, no worries.
I also just added a "Test API" feature to the Setting page.
Update the plugin in Obsidian to check it out:

![Image](https://github.com/user-attachments/assets/3dade358-df4d-4dd0-8105-95c2e28eb5fb)

Also, if you can define multiple custom property names in the "Custom Field Names" tab:
![Image](https://github.com/user-attachments/assets/d87a5de2-04fd-4486-af7f-6fd5886ac201)
