### ISSUE TITLE
Allow "Pinning" of API Fetched Banners

### ISSUE THREAD

**Issue by ltroj** [jparkerweb/pixel-banner#38]
Thanks for this cool plugin, works like a charm!

The only thing that bugs me is that when adding a banner by keyword it will cycle through the fetched images as intended. But usually one of these images fits best and i'd like to keep that specific banner. It would be great if you could show the URL of the current image so we had a chance to copy that URL and set as the banner to keep it.

Or just a small "pin" icon which pins the current banner by writing the image URL directly to the frontmatter when clicked.

**Comment by jparkerweb** [comment]
@ltroj 
Version 2.5.0 of  🚩 Pixel Banner is now available in Obsidian.
Nice 🎁 for you there ;)

![Image](https://github.com/user-attachments/assets/f431b76d-a894-4f93-b6d8-9199853f27e7)

**Comment by ltroj** [comment]
Damn, you're fast!

Thanks a lot, I love it! 🙏

**Comment by jparkerweb** [comment]
https://ko-fi.com/jparkerweb
