### ISSUE TITLE
Unable to install pixel-banner

### ISSUE THREAD

**Issue by marcus-crane** [jparkerweb/pixel-banner#39]
Hey there,

I just came across Pixel Banner and thanks for your efforts! It seems great.

Having said that, I noticed you recently bumped the version in `manifest.json` to v2.5.0.

Upon trying to install Pixel Banner from the Obsidian extension explorer, Obsidian errors out saying that the plugin is unavailable.

While I'm not too familiar with Obsidian's publishing workflow itself, I assume that it scans the manifest version in the base of the repository, tried to find a corresponding Git tag (which doesn't exist yet) and then fails.

In the meantime, I managed to install Pixel Banner using [BRAT](https://github.com/TfTHacker/obsidian42-brat) pinned to v2.4.0 but I figure you may want to be aware for when you cut future releases 🙂

**Comment by jpasholk** [comment]
I had the same issue. But I got it working with your solution with BRAT. Thanks @marcus-crane!

**Comment by jparkerweb** [comment]
@marcus-crane @jpasholk 
You can unpin the version in BRAT now.
I unintentionally pushed an updated `manifest.json` that was meant to go out with the official release this morning.

Thank you for pinging me about this!

Hope you like the "real" v2.5.0 (available now):

![pixel-banner-v2 5 0](https://github.com/user-attachments/assets/e73267a8-5118-4748-b848-38951214077a)
