### ISSUE TITLE
[Feature] Fetch and apply a random banner without frontmatter

### ISSUE THREAD

**Issue by eddienubes** [jparkerweb/pixel-banner#41]
Hey Justin, thank you for a great plugin! 😃

While exploring settings I noticed default keywords section. 
It'd be nice to generate default images based on those keywords, even though "banner" property isn't set in note's frontmatter.

For huge vaults it could quickly drain API quota (since it'd apply to all notes), so we can put it behind a toggle which'll be off by default.

**Comment by jparkerweb** [comment]
@eddienubes have you explored the `Folder Images` tab? It lets you auto-apply images (API or local) to notes in targeted folders (with a toggle to apply to direct children only). I'm pretty sure this will get you close to what you are looking for.

If you just wanted to apply images of cows, chickens, and dogs to your whole vault you could specify a path of `/` and keyword value of `cow, chicken, dog`

![image](https://github.com/user-attachments/assets/cd04e01c-5abf-4ae4-b259-b0b0f5f0b6b7)
