### ISSUE TITLE
🐛 Banner from previous note showing on the current opened note with no banner property

### ISSUE THREAD

**Issue by NekoSensei06** [jparkerweb/pixel-banner#44]
When I open a note with a banner defined in the properties, and then open on the same tab another note without a banner, the banner from the previous note is still displayed : 
![image](https://github.com/user-attachments/assets/862d5d52-f2af-4532-9e17-f16df90fc54d)

It's only on live preview mode.
The banner stays from note to note, until a note with a banner in the properties is opened.
Tried : open from Bookmarks, open from file explorer, open from quick switcher.

No error in Debug console.
Tested on : Desktop Windows

**Comment by jparkerweb** [comment]
@NekoSensei06 
This turned out to be a caching issue.
Fixed in version 2.6.3.
Please update plugin in Obsidian.

Thank you for the bug report 🙏
