### ISSUE TITLE
🐛 Pin icon 📌 displaying on notes without banner

### ISSUE THREAD

**Issue by shuxueshuxue** [jparkerweb/pixel-banner#45]
Pin icon displaying on notes without banner, in both reading and editing view.
Tested on: Desktop Windows

![image](https://github.com/user-attachments/assets/6fbbe693-6f3a-4e2a-b595-873a5dfc0045)

**Comment by jparkerweb** [comment]
@shuxueshuxue 
Fixed in version 2.6.3.
Please update plugin in Obsidian.

Thank you for the bug report 🙏
