### ISSUE TITLE
❓ Content start doesn't work V2.6.4

### ISSUE THREAD

**Issue by wwgb** [jparkerweb/pixel-banner#48]
After updating to version v.2.6.4：
Content-start has no affect in my vault. Even though I have turned off all themes and plugins.
Before version v2.6.4, it could work.
(obsidian: 1.7.4)

**Comment by jparkerweb** [comment]
@wwgb 
Please reference my questions in this similar issue:
https://github.com/jparkerweb/pixel-banner/issues/47

- make sure you have updated the plugin.
- look for any dev tools console errors
- try the example vault
- create your own example value and share with me to reproduce the problem

**Comment by wwgb** [comment]
I downloaded the sample vault zip. The Pixel banner plugin has no problem. However, in my vault, content-start doesn't work. Other things like banner-radius can work. Strangely, just now when I was using Obsidian, I found that content-start worked again.
