### ISSUE TITLE
🦩 Plugin modifies the behavior of floated images/callouts

### ISSUE THREAD

**Issue by aviphyr** [jparkerweb/pixel-banner#49]
While using callouts or images that have a float class, such as using infoboxes in [SIRvb's callouts](https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Snippets/S%20-%20Callouts.css), callouts/images are in their own "block" instead of the normal floating behavior. 

For callouts, it seems like this has to do with the el-div class, which is the parent of the callout div and is usually sized 0x0 when the plugin is disabled, but is sized differently when the plugin is enabled, resulting in the content being pushed down. (In this below example, the size of el-div when the plugin is enabled is 1000x 379.2.)

For images, it seems like the el-p class has similar behaviors to the el-div class for callouts, pushing all the content down when the plugin is enabled. The img just has a simple snippet that has `float:right`

What the note looks like before the plugin is enabled (example with callouts):

![image](https://github.com/user-attachments/assets/10324a6c-545a-4c88-9ce3-5bc3f0ede775)

What it looks like after pixel-banner is enabled:

![image](https://github.com/user-attachments/assets/c7e604d3-3ec1-4260-9495-2c180f204197)

This happens to all notes regardless if there is a banner in the note or not.

Trying a really hacky fix like changing the el-div class height to 0 after the plugin is enabled just results in the the callout being rendered on top of the content below. (probably wasn't going to work anyways but hopefully it gives context) 

![image](https://github.com/user-attachments/assets/f6ccd3bb-7dba-4422-a066-08c70c8acf47)

Using Windows 11, same behavior in a sandbox vault with only the callout snippet and plugin installed, using latest version of Obsidian and of the plugin.

**Comment by jparkerweb** [comment]
resolved in latest update:
https://github.com/jparkerweb/pixel-banner/releases/tag/2.6.7

**Comment by jparkerweb** [comment]
@aviphyr 
checkout v2.7.0 - 🔵🔴 Flickr Time
😂
