### ISSUE TITLE
❓ obsidian file cache

### ISSUE THREAD

**Issue by Leike-Dev** [jparkerweb/pixel-banner#56]
When a new image file is added to the folder, the plugin does not find the image. Even turning it off and reloading it does not find anything in the search.

Perhaps forcing Obsidian to reindex all files could solve the problem, but I don't think that is a good approach.

**Comment by jparkerweb** [comment]
@Leike-Dev can you please show me an example of what you are trying to do? I don't understand what you mean by adding a new image; Do you mean replacing an image, or?

**Comment by jparkerweb** [comment]
just added a new command pallet option to force reload the banner:
![Image](https://github.com/user-attachments/assets/225a9e91-a1ba-4bd7-97fa-8c0b1928b767)

should have a release published very soon.
stay tuned...

**Comment by Leike-Dev** [comment]
I apologize for the delay. 

Well, here is an example. The file "Anotações 2.png", which is marked, does not appear in searches.

![image](https://github.com/user-attachments/assets/ead07816-ccaa-4069-a0c1-c3b4f0f74cab)

**Comment by Leike-Dev** [comment]
### **New tests after update.**

***

This is a new file that has been added to the folder where the plugin has access.
![Part 1](https://github.com/user-attachments/assets/48c51e9d-a38b-47c9-8674-838156457078)

After adding it, I tried to search for it, but nothing was displayed as before.
![Part 2](https://github.com/user-attachments/assets/d5e8bf57-6c97-495b-be59-226cfc08e73b)

However, when adding it manually, like this [[Sky.jpg]], the addition was successful and the banner appeared.
![Part 3](https://github.com/user-attachments/assets/a32dd983-3dbe-4d9d-922f-49c6d40138d2)

And now, when you remove the banner, the file appears without having to add it manually.
![Part 4](https://github.com/user-attachments/assets/d7b2c18f-584f-4049-bd89-dd79444348f0)

***

**Note:**
They appear quickly, but these icons play hide-and-seek on the screen. Nothing that affects use, but it is just an observation. 😉
https://github.com/user-attachments/assets/a4fa61f3-5bdf-486e-ad72-971a96c0aa19

**Comment by jparkerweb** [comment]
@Leike-Dev 

This is more of an Obsidian file search/cache issue. I'm not sure if there is much I can do from my plugin but I will take a look. I have noticed if you start your filename when typing with internal link format, `[[`, and then start typing the file name, it will appear and work properly.

so in your example, in the properties windows in the "banner" property value filed, start typing `[[sk`, and you should be presented with "Sky.jpg" as an option.

I will try to look into this further, but can't make any promises.

**Comment by Leike-Dev** [comment]
You are right about the search mode. I found that out during testing 😅In any case, I appreciate your attention to this. 🥰

**Comment by jparkerweb** [comment]
closing as there isn't anything I can do from the plugin perspective
