### ISSUE TITLE
🖌️ Inline Title Color

### ISSUE THREAD

**Issue by LiamSwayne** [jparkerweb/pixel-banner#60]
It would be useful to be able to set the color of the inline title to contrast a particular image.

**Comment by jparkerweb** [comment]
![Image](https://github.com/user-attachments/assets/748f9a17-e04f-4fb0-b46f-b0d48e8c2626)

**Comment by LiamSwayne** [comment]
Yooo the turnaround is crazy fast!!!! This is a great feature implementation and I will use it often! 🫡 Thanks so much!
