### ISSUE TITLE
❓ Multiple Keywords for Folder Images and Pin/Refresh Always Showing

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pixel-banner#61]
Hello! It appears that this input box does not support multiple keywords at the moment. When more than one word is entered, it becomes invalid and fallback to default images 🤔
![image](https://github.com/user-attachments/assets/c846db5f-b607-4682-94c9-d581ba3378f0)

---

By the way, I have a small suggestion: if a note does not have its banner, should we consider hiding these icons as well?
![image](https://github.com/user-attachments/assets/527540f3-5435-4125-81c0-c39844f42bac)

**Comment by jparkerweb** [comment]
@Moyf for your 1st / main point the Folder images do support multiple keywords. A random word from the comma delimited list is selected and an image matching that search term is returned from one of your Image API's (based on your settings). If you have multiple keywords and multiple APIs setup you could run into a scenario where a keyword doesn't find an image on a certain API, at which point some other random image will be displayed.

Let me know if that doesn't make sense. Please try it again. I can provide an animated gif to show you what I mean if needed.
Thanks for being a power user :)

**Comment by jparkerweb** [comment]
@Moyf for your second point, I don't see the Pin or Refresh icon on any of my notes that don't have a banner applied.
Can you reproduce this in an example vault and share with me?

Thanks.

**Comment by Moyf** [comment]
> @Moyf for your 1st / main point the Folder images do support multiple keywords. A random word from the comma delimited list is selected and an image matching that search term is returned from one of your Image API's (based on your settings). If you have multiple keywords and multiple APIs setup you could run into a scenario where a keyword doesn't find an image on a certain API, at which point some other random image will be displayed.
> 
> Let me know if that doesn't make sense. Please try it again. I can provide an animated gif to show you what I mean if needed. Thanks for being a power user :)

Oh, after several times of refresh, I see the effect!
It seems it was a false alarm, let's ignore this! Thank you for your patience and response!

---

Regarding the second issue, I think I might have encountered an edge case at that time: I entered the banner metadata but cleared it, so the banner disappeared while the button remained: 
! [image](https://github.com/user-attachments/assets/29ee56b2-8989-416c-aafe-e685b0f29798)

In fact, reopening this page wouldn't cause any issues, so I think this doesn't need to be taken seriously either~
