### ISSUE TITLE
content is shown over banner

### ISSUE THREAD

**Issue by N0YC0** [jparkerweb/pixel-banner#62]
<img width="1600" alt="Screenshot 2024-11-14 at 15 55 32" src="https://github.com/user-attachments/assets/62192c48-0ec7-43dd-afb1-0a82ea6cea15">

content is shown over banner. I tried changing where the content starts and it didn't help.

**Comment by jparkerweb** [comment]
Make sure you are on the latest version.
See the attached example vault (`content-push.zip`) and screen shots.
[content-push.zip](https://github.com/user-attachments/files/17754033/content-push.zip)

![image](https://github.com/user-attachments/assets/08eee2fe-7f30-4c7f-98f8-7ca2b8c1ea5a)
![image](https://github.com/user-attachments/assets/a040de28-0754-4068-b47f-110d2e420372)
![image](https://github.com/user-attachments/assets/eed026bc-8bc0-41a6-9d29-3b951d7ea3a6)
![image](https://github.com/user-attachments/assets/381adb55-c352-4acc-90c8-5865cc05df1a)

If you continue to have issues please create a new example vault and attach to an issue so I can have a sample to work from.
Thanks you :)

**Comment by N0YC0** [comment]
Thank you. I solved it. Apparently there were some conflicting commands with the Typewriter Mode Plugin.
