### ISSUE TITLE
‌‌‌Allow setting Inline Title Color to blank.

### ISSUE THREAD

**Issue by WhiteDG** [jparkerweb/pixel-banner#64]
‌‌‌‌‌The new feature "Inline Title Color" introduced in v2.10.0 is great for users who enjoy customizing colors. But I prefer to use the current theme's colors. After enabling this setting without modifying the default configuration, my inline title color turned black(Inline title colour's default value). 
If I want to use the current theme's inline-title-color, I need to find the RGB value and set it manually. Moreover, when I switch themes, I have to repeat this process. 
Therefore, I suggest allowing the "Inline Title Color" setting to be blank, and by default, use the current theme's inline title color.

**Comment by jparkerweb** [comment]
Hi @WhiteDG.
This indeed was an issue I noticed as well (if there wasn't a defined color, or you reset it to default).
This should have been fixed with the v2.10.1 update:
https://github.com/jparkerweb/pixel-banner/releases/tag/2.10.1

Let me know if that still isn't working for you.

**Comment by WhiteDG** [comment]
Hi @jparkerweb 
Thank you for your prompt response and for addressing the issue. I’ve updated to v2.10.1, and I can confirm that the problem is now resolved and everything is working as expected.

I really appreciate your help and the continuous improvements to the project!
