### ISSUE TITLE
❓ Banner Image incorrectly Added?

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pixel-banner#67]
![image](https://github.com/user-attachments/assets/8368eaa4-563c-4e27-bd29-5d48c545e2ed)

The source md:
```markdown
This is an attachment:
! [[obsidian-sync-vault-v0.4.0.zip]]


And this is an image:

! [[2024-11-19-img-241119_160901.jpg]]
```

And it seems that the banner was added incorrectly.

(The note has the Folder Banner configuration applied.)

**Comment by jparkerweb** [comment]
@Moyf 
What do you mean the banner was added incorrectly?
Is it that the content is overlaying your banner?
Without seeing the setting you have for the Folder Banner I can't be sure of what you are seeing.

Do you need to adjust the `content-start` and `banner-height` field values?

Happy to help, just need some more info as I'm not sure what you are asking / reporting.

Thanks :)

**Comment by Moyf** [comment]
> @Moyf What do you mean the banner was added incorrectly?

Ah, I see. It seems that my previous description was too brief, sorry > <
I will provide a more detailed explanation.

This is an image from the my daily note:
![image](https://github.com/user-attachments/assets/f69bcccf-944d-4fd7-973f-c25b39d51d3e)

Checking the Dev Tool can better reveal the structure— **a banner is placed behind this image**:
![image](https://github.com/user-attachments/assets/26402d60-c8b4-4acc-8289-7ff54403be45)

The expected display should be only the image, without the banner behind it.

> 🤔 Perhaps this image is mistakenly identified as an "embedded note"?

By the way, the "embedded files" above it also have a similar issue, but it's not very noticeable because the space is small.
![image](https://github.com/user-attachments/assets/bfbed8c7-0a08-4824-9872-2fc6e1265bd4)

---

In addition, this is my folder configuration:
![image](https://github.com/user-attachments/assets/5e1f5d7b-2896-4270-9cfa-e3663c4fb68b)


And my other notes don't have this issue, images are clean images:
![image](https://github.com/user-attachments/assets/87c6854c-764a-46b5-8a74-8b0d5897fa2d)

Once adding the folder in settings, issue appears:
![image](https://github.com/user-attachments/assets/3247eb9d-dd00-4ee2-93ca-7b77c6f2faf2)

> The Settings:
> ![image](https://github.com/user-attachments/assets/f6f72e09-1dac-4650-87b5-be7643b6b183)

**Comment by jparkerweb** [comment]
here is an example note that has a "forest" banner applied via the Folder Images settings:
![Image](https://github.com/user-attachments/assets/41a095d0-4262-41a8-9594-bd40cc69bdf6)

here are screenshots of that same note with different "content-start" values:
![Image](https://github.com/user-attachments/assets/e92a0b01-93c3-41d6-a54b-da29d2512505)

![Image](https://github.com/user-attachments/assets/fcd72efb-6ecd-4850-bc72-f458d978bc39)

![Image](https://github.com/user-attachments/assets/cc05a85d-b1e6-410d-8373-13f6f59ec1b6)

**Comment by Moyf** [comment]
Ah.. I see.
Actually the "banner" in my demonstration screenshot is not the Note banner on top of my page - which works fine.
It's behind **each of my embedded images**.

For example, if I insert 3 images in my note, I'll got 4 banners: one for the note, and 3 for each of the images.
In your screenshot, the image you embedded is full width. I guess the banner was covered by the image.
Can you try some "longer" images (portrait rather than landscape) and see what happens?

Today I'm on a business trip. When I come back, I will prepare a sample vault for you if it can't be  reproduced. 😇

**Comment by Moyf** [comment]
> Here is a record video, I hope it can explain the issue more clear: https://github.com/user-attachments/assets/148c2f94-73d0-4e92-b160-fea66ab03595
> 
> And this is the testing vault: [Obsidian Sandbox for Banner.zip](https://github.com/user-attachments/files/17841513/Obsidian.Sandbox.for.Banner.zip)

@jparkerweb Hello, just to confirm, could you re-produce this issue?

**Comment by jparkerweb** [comment]
> > Here is a record video, I hope it can explain the issue more clear: https://github.com/user-attachments/assets/148c2f94-73d0-4e92-b160-fea66ab03595
> > And this is the testing vault: [Obsidian Sandbox for Banner.zip](https://github.com/user-attachments/files/17841513/Obsidian.Sandbox.for.Banner.zip)
> 
> [@jparkerweb](https://github.com/jparkerweb) Hello, just to confirm, could you re-produce this issue?

I think I found the issue. In Live Preview mode the plugin is assuming all "embeds" sections are embedded notes, when sometimes they are images (like in your example).

I should have a fix out later today.

Thank you for the example vault.

**Comment by Moyf** [comment]
> > > Here is a record video, I hope it can explain the issue more clear: https://github.com/user-attachments/assets/148c2f94-73d0-4e92-b160-fea66ab03595
> > > And this is the testing vault: [Obsidian Sandbox for Banner.zip](https://github.com/user-attachments/files/17841513/Obsidian.Sandbox.for.Banner.zip)
> > 
> > 
> > [@jparkerweb](https://github.com/jparkerweb) Hello, just to confirm, could you re-produce this issue?
> 
> I think I found the issue. In Live Preview mode the plugin is assuming all "embeds" sections are embedded notes, when sometimes they are images (like in your example).
> 
> I should have a fix out later today.
> 
> Thank you for the example vault.

Yes, you got it!
And sometimes not only images, for instance, if you put a pdf or json file in note as attachments, it would also be considered as embedded notes.

**Comment by Moyf** [comment]
> @Moyf Please update the plugin in Obsidian to the latest version and let me know if this fixes your issue: https://github.com/jparkerweb/pixel-banner/releases/tag/2.10.2
> 
> Thank you!

I think it's fixed now, thank you, Justin!
