### ISSUE TITLE
❓ Setting to disable "Pexels API key is not set" notification

### ISSUE THREAD

**Issue by sethbuchinger** [jparkerweb/pixel-banner#68]
Sweet plugin, but I would ask that you create a way to disable the "Pexels API key is not set. Please set it in the plugin settings" notifications.  Several of them pop up each time Obisidian is started.  In my case, I am only using local images and will not use an external API.

**Comment by jparkerweb** [comment]
Hi @sethbuchinger ,

This may have been addressed in a release just published:
https://github.com/jparkerweb/pixel-banner/releases/tag/2.10.2

I removed API warning messages when entering characters in the `image url and keyword` section of "Folder Image" settings.

Please update the plugin in Obsidian and let me know if this fixes your issue.
Thank you!

**Comment by sethbuchinger** [comment]
Yes, the updated plugin resolves the issue.  Thanks!
