### ISSUE TITLE
❓ How do the APIs work??

### ISSUE THREAD

**Issue by jcesguerram** [jparkerweb/pixel-banner#69]
I cant't figure out which APIs I'm supposed to enter. I keep getting an error.
The images that I have as banners aren't even from Pexels or Pixabay, but the plugin still asks for those APIs. Help please....

**Comment by jparkerweb** [comment]
There were some extra warnings being displayed when entering text in the URL/keyword fields of Folder Image settings.

Please update to the latest version and let me know if this is still a problem for you.

Thank you

**Comment by jcesguerram** [comment]
> There were some extra warnings being displayed when entering text in the URL/keyword fields of Folder Image settings.
> 
> Please update to the latest version and let me know if this is still a problem for you.
> 
> Thank you

It is fixed now, thank you!
One question, does this plugin need the Banners plugin? Or can it replace it? All my previous banners frontmatter was for the Banners plugin

**Comment by jparkerweb** [comment]
This is 100% a stand alone plug-in
