### ISSUE TITLE
🖼️ Button to view Banner Image in fullscreen

### ISSUE THREAD

**Issue by DryIce1** [jparkerweb/pixel-banner#74]
Hello @jparkerweb,

great plugin, thanks! I love the customisation and folder banners.

One thing that I miss from the original banners plugin is that the images were always clickable when used with the Image toolkit plugin (https://github.com/sissilab/obsidian-image-toolkit). It is a plugin that has been around for years and still actively maintained.

- expected behaviour : Here is a screenshot showing the zoom and move image behaviour when clicking on an embedded image in the note body. I would expect that clicking on the pixel banner image would allow the same behaviour.
- current behaviour : pixel banner is not clickable / doesn't zoom.

![image](https://github.com/user-attachments/assets/4ca879cf-09fe-4644-96a4-14da3938dfe8)

all the best!

**Comment by jparkerweb** [comment]
Hi @DryIce1,

Thank you for your suggestion! However, this isn't something I plan to support, as the Banners plugin utilizes the img tag to display images.

🚩 Pixel Banner takes a different, more modern approach by leveraging background-image: url(...). This method avoids interference with the document flow, ensuring better compatibility with other plugins. Additionally, it allows the banner to appear seamlessly "behind" the note content, with options to customize where the content begins on the page.

Switching to accommodate image toolset viewing would unfortunately compromise these benefits, which I believe are core to the plugin's functionality.

I appreciate your understanding—there are always trade-offs, and I hope this explanation provides some clarity!

**Comment by DryIce1** [comment]
Hi @jparkerweb, I appreciate your response and the reasoning behind it. I agree with you that you wouldn't want to compromise other important parts of the plugin 

I'll therefore propose a different method : a button to view the banner image in full.  Display this button similarly to your recent "pin banner" feature. And have settings to turn this function on/off.

**Comment by jparkerweb** [comment]
https://github.com/user-attachments/assets/712a351a-9347-4926-ad91-6d2dd78b2a7a

**Comment by DryIce1** [comment]
Merci, thank you! So good! It makes me want to learn how to create cool obsidian plugin features! Alas, I am a long way from being capable!

**Comment by DryIce1** [comment]
Merci, thank you! So good! It makes me want to learn how to create cool obsidian plugin features! Alas, I am a long way from being capable!

**Comment by jparkerweb** [comment]
@DryIce1 Update the plugin in Obsidian :)

---

## What's New 🎉

### v2.13.0
### ✨ Added
- New view image button icon option to open the banner image in a full-screen modal  
(works with plugins like image toolkit, etc.)

![v2.13.0](https://raw.githubusercontent.com/jparkerweb/ref/refs/heads/main/equill-labs/pixel-banner/pixel-banner-v2.13.0.jpg)

---

Please consider sending me a tip to support my work 😀
# 🍵 [tip me here](https://ko-fi.com/jparkerweb)
⇢ 💻 Visit [eQuill Labs](https://www.quilllabs.com)
⇢ 💬 Join the [Discord](https://discord.gg/sp8AQQhMJ7)
