### ISSUE TITLE
❓ Stretch Images - Readable Line Length

### ISSUE THREAD

**Issue by robsondamota** [jparkerweb/pixel-banner#75]
Hi. Great plugin! Really.

I love all the customization options and the plethora of APIs & images to choose from. It’s fantastic! Thanks for this job.

What I’m missing though is an option to stretch images on top of notes when using reading view and readable line length activated. At the current state, images appear “locked” by the width line I’m using on. I don’t know if it’s something wrong on my part, but images appear stretched only when editing.

Hope this can be achieved and thanks for the amazing plugin.

**Comment by jparkerweb** [comment]
@robsondamota 
Please update the plugin in Obsidian :)
