### ISSUE TITLE
🪰 Horizontal Scrollbar Visible when Note Content isn't Overflowing

### ISSUE THREAD

**Issue by amgedr** [jparkerweb/pixel-banner#79]
Hello,

Wanted to report this minor bug. I'm using the latest version, 2.13.1.

Thanks for the great plugin.

**Comment by jparkerweb** [comment]
Can you please provide a screen shot or to.... or even better an example vault zipped up and attached to this issue?
I can not seem to reproduce your reported issue based on the level of detail you provided.

Thanks!

**Comment by amgedr** [comment]
To replicate it I just created a new vault, installed pixel-banner and created a folder image. I've attached the it to check out.
[Replica1.zip](https://github.com/user-attachments/files/18160095/Replica1.zip)

I should also mention that I use a macbook running MacOS 15.1.1

**Comment by jparkerweb** [comment]
@amgedr 
Thank you for the test vault.

Please update the plugin in Obsidian.
The latest version should address the bottom-padding that Obsidian was added to each Note on load/resize.

Let me know if you find anything else for have feature ideas :)

https://github.com/jparkerweb/pixel-banner/releases/tag/2.13.2

**Comment by jparkerweb** [comment]
![Image](https://github.com/user-attachments/assets/18379caa-ae30-49eb-a2de-dca23af28162)
