### ISSUE TITLE
❓ Dark/Light Mode 

### ISSUE THREAD

**Issue by maliikm** [jparkerweb/pixel-banner#93]
I like to use Pixel Banner with the Border theme and Style Settings plugin which has an automatic light/dark mode setting. When my them changes to the dark settings, the title in my banner becomes unreadable, so I have to set it to a lighter text. But when then when my them switches to the light mode, I have to manually change the title color again. 

I would love to see an inline title color for both light modes and dark mode.

**Comment by jparkerweb** [comment]
@maliikm 
would you mind putting together a quick sample vault (zip it and attach it here) that I can use to reproduce the problem and work out a solution for you?

Thanks so much for the issue report.
🍻 Cheers

**Comment by jparkerweb** [comment]
@maliikm are you having an issue because the dark vs light mode changes the "color" of the title in obsidian?
I would suggest just starting your note content further down the page and/or adjusting the height of the banner.

The readability of the Title on the Pixel Banner solely depends on the banner image you are using and isn't anything I can really accommodate for.  If however you start your page content further down on the note (using the default `content-start` frontmatter field), you can mitigate this issue all together, no matter your dark/light theme.

**Comment by jparkerweb** [comment]
For example, this note has the frontmatter filed set like this:
`content-start: 350`

![Image](https://github.com/user-attachments/assets/ec4adda7-972a-484b-bb3e-781855d7849f)

![Image](https://github.com/user-attachments/assets/3d376706-77f1-41e2-8f26-d94fff8a47d9)

This was I can read the note Title well no matter the dark/light theme.

The only other solution I can think of is having some option to specify a different banner image dependent on the dark/light theme, but unfortunately this is a complicated and heavy lift as it would involve extra complexity around random-shuffle, folder images, and frontmatter settings.... not something I would consider anytime soon as I think the cons far outweigh the pros here.

If I am not understanding the issue, please let me know.

Thanks again for your support.

**Comment by jparkerweb** [comment]
@maliikm ping

**Comment by maliikm** [comment]
Hi Justin, yes I guess the problem is mostly with where the heading starts, as it does start over the image itself, so I'll try out the suggestion to move the title below the banner image. I attached the vault in case you're interested in seeing my setup.



[Text Vault.zip](https://github.com/user-attachments/files/18276560/Text.Vault.zip)

**Comment by jparkerweb** [comment]
Thanks for the info @maliikm 

Please let me know with another issue or our Discord if you have any other feature requests/bugs 😀

[eQuill Labs Discord Link](https://discord.gg/sp8AQQhMJ7)

**Comment by jparkerweb** [comment]
@maliikm I took a look at the same vault (thank you), and if you are just wanting to set a color for the "inline note title" for dark vs light mode I could add some custom frontmatter settings to let you control that.

so in your frontmatter maybe it would look like
```
---
banner-title-dark-light-colors: #eee,maroon
---
```

where you could define two colors (comma separated)... the first for the title in dark mode and the second for the title color in light mode?

Let me know if this would be helpful.
Thanks again.

if you haven't already I would greatly appreciate a ⭐ on the GitHub repo 🙏
https://github.com/jparkerweb/pixel-banner
