### ISSUE TITLE
🐛 "--pixel-banner-scrollbar-width" sized gap on the left of the banner

### ISSUE THREAD

**Issue by kazerniel** [jparkerweb/pixel-banner#94]
**Describe the bug**
I set up the plugin with only general settings, but a mysterious gap appears on the left side of each banner. After some poking around in the code inspector in Obsidian, it seems to have the exact width as the "--pixel-banner-scrollbar-width" variable. As I change that value in the inspector, so changes the gap.

**Screenshots**
![image](https://github.com/user-attachments/assets/e89b4d40-5259-4bcb-936d-f65e4d3cf58e)

**Environment:**
 - OS: Win10
 - Obsidian Version (if applicable): 1.7.7
 - Other Details: I'm using Prism theme v3.6.0. I tried it out with all my custom css disabled, and the gap remains.

**Comment by jparkerweb** [comment]
@kazerniel yup, this was a design decision and 100% intentional, but good eye 👁️

![image](https://github.com/user-attachments/assets/95937e82-c708-4af0-a21a-7f4da07333a4)

especially "balanced" if you have a note that isn't long enough to even have a scrollbar 😉

**Comment by kazerniel** [comment]
Sadly I only have it on the left side, not the right, so it's more unbalanced this way 😅 Anyway, I just set the variable to zero in my local CSS.
