### ISSUE TITLE
⚖️ Add Pagination Controls to Image Selector Modal

### ISSUE THREAD

**Issue by renatomen** [jparkerweb/pixel-banner#98]
Hey @jparkerweb , great work with the plugin. I was going to tinker with the old obsidian-banner plugin to see if I could make it work in Edit mode when I realised you had just released the pixel-banner plugin 🙏🏻.

**Issue**
Given that I have thousands of images in my obsidian vault, when I use the image selection modal to select a local image, my obsidian becomes unresponsive as the image previews are loaded as it appears that the plugin is trying to load all images.

**Describe the solution you'd like**
I'd like to have the ability to use the plugin settings to define the maximum number of images to be loaded by the image selector when choosing local images. 

The selector would select the "TOP <Settings.MaxImageLoaded>" sorted by  <Settings.SortOrder>. 

The "Sort Order" could be "Modified Date" by default, which would allow images recently added to the vault to be at the top.

 

**Describe alternatives you've considered**
Another alternative that could be implemented in isolation or in conjunction to my suggestion is pagination. Only a first page of images would be loaded. Subsequent pages would only be loaded "on demand".

If used in conjunction with the original suggestion, the Max number could be a "Max images per page"

**Additional context**
The old obsidian-banner plugin offered the ability to limit the images in the image selection modal. It worked very well in my large vault

Thank you!

**Comment by jparkerweb** [comment]
@renatomen Great idea!
The image selection modal is a fairly newish feature, but I will be sure to address this soon, as I can see how lots of images can be an issue.

Say tuned!

**Comment by jparkerweb** [comment]
@renatomen 

![Image](https://github.com/user-attachments/assets/02e2d172-2164-4a6a-8bb0-bff4dbbe7ec9)

https://github.com/jparkerweb/pixel-banner/releases/tag/2.17.0

Update the Plugin in Obsidian 😀

**Comment by renatomen** [comment]
Thank you @jparkerweb for implementing that so quickly!
It worked like a charm on Desktop and Android!
